---
name: CI
"on":
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'
          cache: npm
      - run: npm install
      - run: npm test
